# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - apt-get update --yes
 - apt-get install --yes cmake
 - apt-get install --yes libasound2-dev libcurl4-openssl-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev libjack-jackd2-dev lv2-dev
 - |
  wget https://github.com/Kitware/CMake/releases/download/v3.22.4/cmake-3.22.4-linux-x86_64.tar.gz
  mkdir cmake-install
  tar -xvzf cmake-3.22.4-linux-x86_64.tar.gz -C cmake-install

build:
  stage: build
  script:
    - cmake-install/cmake-3.22.4-linux-x86_64/bin/cmake --version
    - cmake-install/cmake-3.22.4-linux-x86_64/bin/cmake -Bbuild
    - cmake-install/cmake-3.22.4-linux-x86_64/bin/cmake --build build --parallel 4
    - ./build/SimplePlugin --unit-tests --all
